check if file transfer was successful or not

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -5,3 +5,9 @@ if [[ "$#" -lt 4 ]]; then
 else
 	scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
 fi
+# Checks if the transfer was successful or failed
+if [[ $? -eq 0 ]]; then
+  echo "FILE TRANSFER WAS SUCCESSFUL"
+else
+  echo "FILE TRANSFER FAILED"
+fi
